version: '3.8'

services:
  product:
    build: microservices/product-service
    deploy:
      resources:
        limits:
          memory: 350M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  recommendation:
    build: microservices/recommendation-service
    deploy:
      resources:
        limits:
          memory: 350M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  review:
    build: microservices/review-service
    deploy:
      resources:
        limits:
          memory: 350M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql

  product-composite:
    build: microservices/product-composite-service
    deploy:
      resources:
        limits:
          memory: 350M
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # $ mongo
  mongodb:
    platform: linux/x86_64
    image: mongo:3.6.9
    deploy:
      resources:
        limits:
          memory: 350M
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    deploy:
      resources:
        limits:
          memory: 350M
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
